name: Deploy Komari Panel to SAP CF

on:
  workflow_dispatch:


env:
  IMAGE: komari/komari:latest
  MEMORY: 1024M
  DISK: 2048M


jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Install CF CLI
      shell: bash
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -

        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list

        sudo apt update

        sudo apt install -y cf8-cli


    - name: Login SAP Cloud Foundry
      shell: bash
      env:
        CF_API: ${{ secrets.CF_API }}
        CF_USER: ${{ secrets.CF_USER }}
        CF_PASS: ${{ secrets.CF_PASS }}

      run: |

        CF_API=$(echo "$CF_API" | tr -d '\r\n')
        CF_USER=$(echo "$CF_USER" | tr -d '\r\n')
        CF_PASS=$(echo "$CF_PASS" | tr -d '\r\n')

        echo "Set API"
        cf api "$CF_API"

        echo "Login"
        cf auth "$CF_USER" "$CF_PASS"

        echo "Login success"

        cf target



    - name: Auto Select Org And Space
      shell: bash
      run: |

        echo "========== ORG LIST =========="

        cf orgs


        ORG=$(cf orgs | \
        sed '1,/name/d' | \
        sed '/^$/d' | \
        head -n 1)


        echo "Detected ORG:"
        echo "$ORG"



        if [ -z "$ORG" ]; then
          echo "No organization found"
          exit 1
        fi



        echo "========== SPACE LIST =========="


        cf target -o "$ORG"


        cf spaces



        SPACE=$(cf spaces | \
        sed '1,/name/d' | \
        sed '/^$/d' | \
        head -n 1)



        echo "Detected SPACE:"
        echo "$SPACE"



        if [ -z "$SPACE" ]; then
          echo "No space found"
          exit 1
        fi



        echo "ORG=$ORG" >> $GITHUB_ENV
        echo "SPACE=$SPACE" >> $GITHUB_ENV



        echo "Targeting CF..."

        cf target \
          -o "$ORG" \
          -s "$SPACE"



        cf target



    - name: Deploy Komari

      shell: bash

      run: |

        APP_NAME="komari-panel-$(date +%s)"

        echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV


        echo "Deploying $APP_NAME"



        cf push "$APP_NAME" \
          --docker-image "$IMAGE" \
          -m "$MEMORY" \
          -k "$DISK" \
          --health-check-type port



    - name: Check Application

      shell: bash

      run: |

        cf app "$APP_NAME"



    - name: Show URL

      shell: bash

      run: |

        ROUTE=$(cf app "$APP_NAME" | grep routes | awk '{print $2}')


        echo "================================"

        echo "Komari deployed successfully"

        echo ""

        echo "URL:"
        echo "https://$ROUTE"

        echo "================================"
