    - name: Select Org and Space
      shell: bash
      run: |

        echo "Getting org list..."

        ORG=$(cf orgs | grep -v "Getting" | grep -v "^name" | grep -v "^$" | head -n 1)

        echo "ORG=$ORG"


        if [ -z "$ORG" ]; then
          echo "No org found"
          exit 1
        fi


        echo "Getting spaces..."


        cf target -o "$ORG"


        SPACE=$(cf spaces | grep -v "Getting" | grep -v "^name" | grep -v "^$" | head -n 1)


        echo "SPACE=$SPACE"


        if [ -z "$SPACE" ]; then
          echo "No space found"
          exit 1
        fi


        echo "ORG=$ORG" >> $GITHUB_ENV
        echo "SPACE=$SPACE" >> $GITHUB_ENV


        cf target -o "$ORG" -s "$SPACE"
